In [4]:
import numpy as np
e1 = [ 1,-1, 1,-1, 1,-1]
e2 = [-1, 1,-1, 1,-1, 1]
e3 = [ 1, 1, 1, 1, 1, 1]

V = [ [ 1,-1, 1, 1,-1,1],
      [-1, 1, 1,-1,1,-1],
      [1, 1, 1,-1,-1,-1],
      [-1,-1,-1, 1, 1,1],
      [ 1, 1, 1, 1, 1 ,1],
      [-1,-1,1,-1,-1,-1],
      [-1,-1,-1,1,-1,-1],
      [ 1, 1,-1,-1, 1, 1],
      [ 1, 1,-1, 1, 1, 1],
      [ 1, 1, 1,-1, 1, 1]]
V = np.array(V)

In [5]:
W = [[0.5,-0.5,0.5],
     [-0.5,0.5,0.5],
     [0.5,-0.5,0.5],
     [-0.5,0.5,0.5],
     [0.5,-0.5,0.5],
     [-0.5,0.5,0.5]]
W = np.array(W)
b = 6/2

In [6]:
import numpy as np
def MaxNet(x):

    E = 0.15
    w = [[1,-0.15,-0.15],
         [-0.15,1,-0.15],
         [-0.15,-0.15,1]]
    w = np.array(w)


    cond = True
    a = np.copy(x)

    while cond:
        a_last = np.copy(a)
        for i in range(len(a)):
            sumj = 0
            for j in range(len(a)):
                if i != j:
                    sumj = sumj + a_last[j]
            if a_last[i] - E * sumj <= 0:
                a[i] = 0
            else:
                a[i] = a_last[i] - E * sumj
        print(a)
        n = np.count_nonzero(a == 0, axis = 0)
        if(3 - n == 1):
            cond = False 
    return np.where(a != 0)[0][0] + 1

In [7]:
result = []
for v in V :
    nodes = []
    for j in range(W.shape[1]):
        sumj = 0
        for i in range(W.shape[0]):
             sumj = sumj + v[i]*W[i][j]
        nodes.append(b + sumj)
    result.append('Y' + str(MaxNet(np.array(nodes))))

[1.95 1.95 3.1 ]
[1.1925 1.1925 2.515 ]
[0.636375 0.636375 2.15725 ]
[0.21733125 0.21733125 1.9663375 ]
[0.         0.         1.90113813]
[3.25 0.95 2.1 ]
[2.7925 0.1475 1.47  ]
[2.549875 0.       1.029   ]
[2.395525   0.         0.64651875]
[2.29854719 0.         0.28719   ]
[2.25546869 0.         0.        ]
[3.25 0.95 2.1 ]
[2.7925 0.1475 1.47  ]
[2.549875 0.       1.029   ]
[2.395525   0.         0.64651875]
[2.29854719 0.         0.28719   ]
[2.25546869 0.         0.        ]
[0.95 3.25 2.1 ]
[0.1475 2.7925 1.47  ]
[0.       2.549875 1.029   ]
[0.         2.395525   0.64651875]
[0.         2.29854719 0.28719   ]
[0.         2.25546869 0.        ]
[1.65 1.65 5.1 ]
[0.6375 0.6375 4.605 ]
[0.      0.      4.41375]
[3.55 1.25 0.1 ]
[3.3475 0.7025 0.    ]
[3.242125 0.200375 0.      ]
[3.21206875 0.         0.        ]
[1.25 3.55 0.1 ]
[0.7025 3.3475 0.    ]
[0.200375 3.242125 0.      ]
[0.         3.21206875 0.        ]
[1.95 1.95 3.1 ]
[1.1925 1.1925 2.515 ]
[0.636375 0.636375 2.1572

In [8]:
result

['Y3', 'Y1', 'Y1', 'Y2', 'Y3', 'Y1', 'Y2', 'Y3', 'Y3', 'Y3']