In [1]:
import numpy as np
x = [1.2,1.1,1,0.9,0.95,1.15]
x = np.array(x)
w = [[1,-0.15,-0.15,-0.15,-0.15,-0.15],
     [-0.15,1,-0.15,-0.15,-0.15,-0.15],
     [-0.15,-0.15,1,-0.15,-0.15,-0.15],
     [-0.15,-0.15,-0.15,1,-0.15,-0.15],
     [-0.15,-0.15,-0.15,-0.15,1,-0.15],
     [-0.15,-0.15,-0.15,-0.15,-0.15,1]]
w = np.array(w)

In [3]:
cond = True
a = np.copy(x)
E = 0.05
while cond:
    a_last = np.copy(a)
    for i in range(len(a)):
        sumj = 0
        for j in range(len(a)):
            if i != j:
                sumj = sumj + a_last[j]
        if a_last[i] - E * sumj <= 0:
            a[i] = 0
        else:
            a[i] = a_last[i] - E * sumj
    print(a)
    n = np.count_nonzero(a == 0, axis = 0)
    if(6 - n == 1):
        cond = False     

[0.945  0.84   0.735  0.63   0.6825 0.8925]
[0.756    0.64575  0.5355   0.42525  0.480375 0.700875]
[0.6166125  0.50085    0.3850875  0.269325   0.32720625 0.55873125]
[0.5145525  0.39300188 0.27145125 0.14990063 0.21067594 0.45377719]
[0.44061216 0.312984   0.18535584 0.05772769 0.12154177 0.37679808]
[0.38789179 0.25388222 0.11987266 0.         0.05286788 0.32088701]
[0.3505163  0.20980626 0.06909621 0.         0.         0.28016128]
[0.32256311 0.17481757 0.02707202 0.         0.         0.24869034]
[0.30003412 0.14490129 0.         0.         0.         0.2224677 ]
[0.28166567 0.1187762  0.         0.         0.         0.20022093]
[0.26571581 0.09468187 0.         0.         0.         0.18019884]
[0.25197177 0.07238614 0.         0.         0.         0.16217896]
[0.24024352 0.0516786  0.         0.         0.         0.14596106]
[0.23036153 0.03236837 0.         0.         0.         0.13136495]
[0.22217487 0.01428205 0.         0.         0.         0.11822846]
[0.21554934 0.  

In [2]:
cond = True
a = np.copy(x)
E = 0.1
while cond:
    a_last = np.copy(a)
    for i in range(len(a)):
        sumj = 0
        for j in range(len(a)):
            if i != j:
                sumj = sumj + a_last[j]
        if a_last[i] - E * sumj <= 0:
            a[i] = 0
        else:
            a[i] = a_last[i] - E * sumj
    print(a)
    n = np.count_nonzero(a == 0, axis = 0)
    if(6 - n == 1):
        cond = False     

[0.69  0.58  0.47  0.36  0.415 0.635]
[0.444  0.323  0.202  0.081  0.1415 0.3835]
[0.3309  0.1978  0.0647  0.      0.      0.26435]
[0.278215 0.131805 0.       0.       0.       0.20501 ]
[0.2445335 0.0834825 0.        0.        0.        0.164008 ]
[0.21978445 0.04262835 0.         0.         0.         0.1312064 ]
[0.20240097 0.00752927 0.         0.         0.         0.10496512]
[0.19115154 0.         0.         0.         0.         0.0839721 ]
[0.18275433 0.         0.         0.         0.         0.06485694]
[0.17626863 0.         0.         0.         0.         0.04658151]
[0.17161048 0.         0.         0.         0.         0.02895465]
[0.16871502 0.         0.         0.         0.         0.0117936 ]
[0.16753566 0.         0.         0.         0.         0.        ]


# part 2)

In [14]:
cond = True
a = np.copy(x)
E = 0.01
while cond:
    a_last = np.copy(a)
    for i in range(len(a)):
        sumj = 0
        for j in range(len(a)):
            if i != j:
                sumj = sumj + a_last[j]
        if a_last[i] - E * sumj <= 0.6:
            a[i] = 0.6
        else:
            a[i] = a_last[i] - E * sumj
    print(a)
    n = np.count_nonzero(a == 0.6, axis = 0)
    if(6 - n <= 1):
        cond = False 

[1.149  1.048  0.947  0.846  0.8965 1.0985]
[1.10064  0.99863  0.89662  0.79461  0.845615 1.049635]
[1.0547889  0.9517588  0.8487287  0.7456986  0.79721365 1.00327385]
[1.01132216 0.90726176 0.80320136 0.69914096 0.75117116 0.95929196]
[0.97012149 0.86502049 0.75991948 0.65481848 0.70736898 0.91757099]
[0.93107451 0.82492249 0.71877048 0.61261846 0.66569447 0.8779985 ]
[0.89407446 0.78686093 0.67964739 0.6        0.62604063 0.8404677 ]
[0.8587443  0.75045863 0.64217296 0.6        0.6        0.80460146]
[0.82477197 0.71540344 0.60603491 0.6        0.6        0.7700877 ]
[0.79185671 0.68139449 0.6        0.6        0.6        0.7366256 ]
[0.75967651 0.64810967 0.6        0.6        0.6        0.70389309]
[0.72815648 0.61547397 0.6        0.6        0.6        0.67181523]
[0.69728359 0.6        0.6        0.6        0.6        0.64037892]
[0.6668798  0.6        0.6        0.6        0.6        0.60940609]
[0.63678574 0.6        0.6        0.6        0.6        0.6       ]


In [24]:
cond = True
a = np.copy(x)
a = a - [0.8 for i in range(len(a))]
while cond:
    a_last = np.copy(a)
    for i in range(len(a)):
        sumj = 0
        for j in range(len(a)):
            if i != j:
                sumj = sumj + a_last[j]
        if a_last[i] - E * sumj <= 0:
            a[i] = 0
        else:
            a[i] = a_last[i] - E * sumj
    print(a)
    n = np.count_nonzero(a == 0, axis = 0)
    if(6 - n == 1):
        cond = False 

[0.235  0.12   0.005  0.     0.     0.1775]
[0.189625 0.057375 0.       0.       0.       0.1235  ]
[0.16249375 0.01040625 0.         0.         0.         0.08645   ]
[0.14796531 0.         0.         0.         0.         0.060515  ]
[0.13888806 0.         0.         0.         0.         0.0383202 ]
[0.13314003 0.         0.         0.         0.         0.01748699]
[0.13051698 0.         0.         0.         0.         0.        ]


# part3)

In [99]:
sortL = []
x_main = [1.2,1.1,1,0.9,0.95,1.15]
x_main = np.array(x_main)
w = [[1,-0.15,-0.15,-0.15,-0.15,-0.15],
     [-0.15,1,-0.15,-0.15,-0.15,-0.15],
     [-0.15,-0.15,1,-0.15,-0.15,-0.15],
     [-0.15,-0.15,-0.15,1,-0.15,-0.15],
     [-0.15,-0.15,-0.15,-0.15,1,-0.15],
     [-0.15,-0.15,-0.15,-0.15,-0.15,1]]
w = np.array(w)
x = np.copy(x_main)
def MaxNet(x):
    print('input : ',x)
    
    cond = True
    a = np.copy(x)
    E = 0.05
    while cond:
        a_last = np.copy(a)
        for i in range(len(a)):
            sumj = 0
            for j in range(len(a)):
                if i != j:
                    sumj = sumj + a_last[j]
            if a_last[i] - E * sumj <= 0:
                a[i] = 0
            else:
                a[i] = a_last[i] - E * sumj
#         print(a)
        n = np.count_nonzero(a == 0, axis = 0)
        if(len(x) - n <= 1):
            print('output : ',a)
            cond = False
            maxind = np.where(a != 0)
            if(len(maxind[0])>0):
                sortL.append(maxind[0][0])
                x[maxind[0][0]] = 0
                print('')
                MaxNet(x)

In [100]:
MaxNet(x)

input :  [1.2  1.1  1.   0.9  0.95 1.15]
output :  [0.18490041 0.         0.         0.         0.         0.        ]

input :  [0.   1.1  1.   0.9  0.95 1.15]
output :  [0.         0.         0.         0.         0.         0.20484974]

input :  [0.   1.1  1.   0.9  0.95 0.  ]
output :  [0.         0.29274552 0.         0.         0.         0.        ]

input :  [0.   0.   1.   0.9  0.95 0.  ]
output :  [0.         0.         0.21687606 0.         0.         0.        ]

input :  [0.   0.   0.   0.9  0.95 0.  ]
output :  [0.         0.         0.         0.         0.29068366 0.        ]

input :  [0.  0.  0.  0.9 0.  0. ]
output :  [0.  0.  0.  0.9 0.  0. ]

input :  [0. 0. 0. 0. 0. 0.]
output :  [0. 0. 0. 0. 0. 0.]


In [94]:
for i in sortL:
    print(x_main[i])

1.2
1.15
1.1
1.0
0.95
0.9


# part 4)

In [108]:
x = [1.2,1.1,1,0.9,0.95,1.15]
x = np.array(x)
w = [[1,-0.15,-0.15,-0.15,-0.15,-0.15],
     [-0.15,1,-0.15,-0.15,-0.15,-0.15],
     [-0.15,-0.15,1,-0.15,-0.15,-0.15],
     [-0.15,-0.15,-0.15,1,-0.15,-0.15],
     [-0.15,-0.15,-0.15,-0.15,1,-0.15],
     [-0.15,-0.15,-0.15,-0.15,-0.15,1]]
w = np.array(w)
E = 0.05
cond = True
a = np.copy(x)
sortL = []
while cond:
    a_last = np.copy(a)
    for i in range(len(a)):
        sumj = 0
        for j in range(len(a)):
            if i != j:
                sumj = sumj + a_last[j]
        if a_last[i] - E * sumj <= 0:
            a[i] = 0
            if (i not in sortL):
                sortL.append(i)
        else:
            a[i] = a_last[i] - E * sumj
    print(a)
    n = np.count_nonzero(a == 0, axis = 0)
    if(6 - n <= 1):
        sortL.append(np.where(a != 0)[0][0])
        cond = False

result = []
for k in sortL:
    result.append(x[k])


[0.945  0.84   0.735  0.63   0.6825 0.8925]
[0.756    0.64575  0.5355   0.42525  0.480375 0.700875]
[0.6166125  0.50085    0.3850875  0.269325   0.32720625 0.55873125]
[0.5145525  0.39300188 0.27145125 0.14990063 0.21067594 0.45377719]
[0.44061216 0.312984   0.18535584 0.05772769 0.12154177 0.37679808]
[0.38789179 0.25388222 0.11987266 0.         0.05286788 0.32088701]
[0.3505163  0.20980626 0.06909621 0.         0.         0.28016128]
[0.32256311 0.17481757 0.02707202 0.         0.         0.24869034]
[0.30003412 0.14490129 0.         0.         0.         0.2224677 ]
[0.28166567 0.1187762  0.         0.         0.         0.20022093]
[0.26571581 0.09468187 0.         0.         0.         0.18019884]
[0.25197177 0.07238614 0.         0.         0.         0.16217896]
[0.24024352 0.0516786  0.         0.         0.         0.14596106]
[0.23036153 0.03236837 0.         0.         0.         0.13136495]
[0.22217487 0.01428205 0.         0.         0.         0.11822846]
[0.21554934 0.  

In [109]:
result

[0.9, 0.95, 1.0, 1.1, 1.15, 1.2]