In [43]:
A = [[-1,-1,-1, 1,-1,-1,-1,
     -1,-1,-1, 1,-1,-1,-1,
     -1,-1, 1,-1, 1,-1,-1,
     -1,-1, 1,-1, 1,-1,-1,
     -1,-1, 1, 1, 1,-1,-1,
     -1, 1,-1,-1,-1, 1,-1,
     -1, 1,-1,-1,-1, 1,-1,
      1,-1,-1,-1,-1,-1, 1,
      1,-1,-1,-1,-1,-1, 1]]

a = [[-1, 1,-1,
       1,-1, 1,
       1, 1, 1,
       1,-1, 1,
       1,-1, 1]]


B = [[ 1, 1, 1, 1, 1,-1,-1 ,
       1,-1,-1,-1,-1, 1,-1 ,
       1,-1,-1,-1,-1,-1, 1 ,
       1,-1,-1,-1,-1, 1,-1 ,
       1, 1, 1, 1, 1,-1,-1 ,
       1,-1,-1,-1,-1, 1,-1 ,
       1,-1,-1,-1,-1,-1, 1 ,
       1,-1,-1,-1,-1, 1,-1 ,
       1, 1, 1, 1, 1,-1, 1]]

b = [[ 1, 1,-1 ,
       1,-1, 1 ,
       1, 1,-1 ,
       1,-1, 1 ,
       1, 1,-1]]

C = [[-1,-1, 1, 1, 1,-1,-1 ,
      -1, 1,-1,-1,-1, 1,-1 ,
       1,-1,-1,-1,-1,-1, 1 ,
       1,-1,-1,-1,-1,-1,-1 ,
       1,-1,-1,-1,-1,-1,-1 ,
       1,-1,-1,-1,-1,-1,-1 ,
       1,-1,-1,-1,-1,-1, 1 ,
      -1, 1,-1,-1,-1, 1,-1 ,
      -1,-1, 1, 1, 1,-1,-1]]

c = [[ 1, 1, 1 ,
       1,-1,-1 ,
       1,-1,-1 ,
       1,-1,-1 ,
       1, 1, 1]]

In [2]:
import numpy as np
W = np.outer(A,a) + np.outer(B,b) + np.outer(C,c)

In [3]:
W.shape

(63, 15)

In [4]:
xA = (np.array(A)).dot(np.array(W))
tA = np.sign(xA)
comparison = tA == a
comparison.all()

True

In [5]:
xB = (np.array(B)).dot(np.array(W))
tB = np.sign(xB)
comparison = tB == b
comparison.all()

True

In [6]:
xC = (np.array(C)).dot(np.array(W))
tC = np.sign(xC)
comparison = tC == c
comparison.all()

True

In [7]:
np.array(A).dot(np.transpose(B))

array([[5]])

In [8]:
np.array(A).dot(np.transpose(C))

array([[-1]])

In [9]:
np.array(B).dot(np.transpose(C))

array([[33]])

# part2

In [107]:
import random
def noise(n,loss):
    trueans = 0
    for ep in range(n):
        char = random.randint(0,2)
        if(char == 0):
            As = np.copy(A)
            index = random.sample(range(len(A[0])), int(loss*len(A[0])))
            for i in index:
                As[0][i] = As[0][i]*-1
            xAs = (np.array(As)).dot(np.array(W))
            tAs = np.sign(xAs)
            comparison = tAs == a
            if (comparison.all()):
                trueans += 1
        if(char == 1):
            Bs = np.copy(B)
            index = random.sample(range(len(Bs[0])), int(loss*len(Bs[0])))
            for i in index:
                Bs[0][i] = Bs[0][i]*-1
            xBs = (np.array(Bs)).dot(np.array(W))
            tBs = np.sign(xBs)
            comparison = tBs == b
            if (comparison.all()):
                trueans += 1
        if(char == 2):
            Cs = np.copy(C)
            index = random.sample(range(len(Cs[0])), int(loss*len(Cs[0])))
            for i in index:
                Cs[0][i] = Cs[0][i]*-1
            xCs = (np.array(Cs)).dot(np.array(W))
            tCs = np.sign(xCs)
            comparison = tCs == c
            if (comparison.all()):
                trueans += 1
#     print('true answers in ',n,' data with noise',loss,'is ',trueans*100/n)   
    return trueans*100/n

In [100]:

noise(1000,0.1)
noise(1000,0.11)
noise(1000,0.12)
noise(1000,0.13)
noise(1000,0.14)
noise(1000,0.15)
noise(1000,0.2)
noise(1000,0.3)
noise(1000,0.4)
noise(1000,0.5)
noise(1000,0.6)
noise(1000,0.7)
noise(1000,0.8)
noise(1000,0.9)

true answers in  1000  data with noise 0.1 is  100.0
true answers in  1000  data with noise 0.11 is  100.0
true answers in  1000  data with noise 0.12 is  100.0
true answers in  1000  data with noise 0.13 is  99.9
true answers in  1000  data with noise 0.14 is  100.0
true answers in  1000  data with noise 0.15 is  99.6
true answers in  1000  data with noise 0.2 is  98.7
true answers in  1000  data with noise 0.3 is  86.4
true answers in  1000  data with noise 0.4 is  54.0
true answers in  1000  data with noise 0.5 is  0.0
true answers in  1000  data with noise 0.6 is  0.0
true answers in  1000  data with noise 0.7 is  0.0
true answers in  1000  data with noise 0.8 is  0.0
true answers in  1000  data with noise 0.9 is  0.0


# part3

In [105]:
import random
def lossInfo(n,loss):
    trueans = 0
    for ep in range(n):
        char = random.randint(0,2)
    #     print(char)
        if(char == 0):
            As = np.copy(A)
            index = random.sample(range(len(A[0])), int(loss*len(A[0])))
            for i in index:
                As[0][i] = 0
            xAs = (np.array(As)).dot(np.array(W))
            tAs = np.sign(xAs)
            comparison = tAs == a
            if (comparison.all()):
                trueans += 1
        if(char == 1):
            Bs = np.copy(B)
            index = random.sample(range(len(Bs[0])), int(loss*len(Bs[0])))
            for i in index:
                Bs[0][i] = 0
            xBs = (np.array(Bs)).dot(np.array(W))
            tBs = np.sign(xBs)
            comparison = tBs == b
            if (comparison.all()):
                trueans += 1
        if(char == 2):
            Cs = np.copy(C)
            index = random.sample(range(len(Cs[0])), int(loss*len(Cs[0])))
            for i in index:
                Cs[0][i] = 0
            xCs = (np.array(Cs)).dot(np.array(W))
            tCs = np.sign(xCs)
            comparison = tCs == c
            if (comparison.all()):
                trueans += 1
    print('true answers in ',n,' data with loss',loss,'is ',trueans*100/n)   
   

In [96]:

lossInfo(1000,0.1)
lossInfo(1000,0.2)
lossInfo(1000,0.3)
lossInfo(1000,0.4)
lossInfo(1000,0.5)
lossInfo(1000,0.6)
lossInfo(1000,0.7)
lossInfo(1000,0.8)
lossInfo(1000,0.9)
lossInfo(1000,0.93)
lossInfo(1000,0.95)
lossInfo(1000,0.99)


true answers in  1000  data with loss 0.1 is  100.0
true answers in  1000  data with loss 0.2 is  100.0
true answers in  1000  data with loss 0.3 is  100.0
true answers in  1000  data with loss 0.4 is  100.0
true answers in  1000  data with loss 0.5 is  99.5
true answers in  1000  data with loss 0.6 is  98.2
true answers in  1000  data with loss 0.7 is  97.2
true answers in  1000  data with loss 0.8 is  89.3
true answers in  1000  data with loss 0.9 is  74.5
true answers in  1000  data with loss 0.93 is  65.3
true answers in  1000  data with loss 0.95 is  41.6
true answers in  1000  data with loss 0.99 is  0.0


# part5

In [109]:
x = 0
for i in range(100):
    x = x + noise(1000,0.1)
print("mean 10% : ",x/100)

x = 0
for i in range(100):
    x = x + noise(1000,0.11)
print("mean 11% : ",x/100)
    
x = 0
for i in range(100):
    x = x + noise(1000,0.12)
print("mean 12% : ",x/100)

x = 0
for i in range(100):
    x = x + noise(1000,0.13)
print("mean 13% : ",x/100)

x = 0
for i in range(100):
    x = x + noise(1000,0.14)
print("mean 14% : ",x/100)

x = 0
for i in range(100):
    x = x + noise(1000,0.15)
print("mean 15% : ",x/100)

x = 0
for i in range(100):
    x = x + noise(1000,0.16)
print("mean 16% : ",x/100)

x = 0
for i in range(100):
    x = x + noise(1000,0.17)
print("mean 17% : ",x/100)

mean 10% :  99.98899999999996
mean 11% :  99.995
mean 12% :  99.93699999999994
mean 13% :  99.88799999999992
mean 14% :  99.88799999999992
mean 15% :  99.60000000000002
mean 16% :  99.36599999999997
mean 17% :  99.42399999999996


In [112]:
x = 0
for i in range(100):
    x = x + noise(1000,0.05)
print("mean 5% : ",x/100)

x = 0
for i in range(100):
    x = x + noise(1000,0.06)
print("mean 6% : ",x/100)

x = 0
for i in range(100):
    x = x + noise(1000,0.07)
print("mean 7% : ",x/100)

x = 0
for i in range(100):
    x = x + noise(1000,0.08)
print("mean 8% : ",x/100)

x = 0
for i in range(100):
    x = x + noise(1000,0.09)
print("mean 9% : ",x/100)

mean 5% :  100.0
mean 6% :  100.0
mean 7% :  100.0
mean 8% :  99.99699999999999
mean 9% :  99.99599999999998
