In [1]:
S= [1,1,1,-1]

# part1

In [2]:
import numpy as np
W = np.outer(S,S) - np.identity(len(S))

In [3]:
W

array([[ 0.,  1.,  1., -1.],
       [ 1.,  0.,  1., -1.],
       [ 1.,  1.,  0., -1.],
       [-1., -1., -1.,  0.]])

# part2

In [4]:
S2 = [1,1,-1,1]
W2 = np.outer(S2,S2) + np.outer(S,S) - 2*np.identity(4)

In [5]:
W2

array([[ 0.,  2.,  0.,  0.],
       [ 2.,  0.,  0.,  0.],
       [ 0.,  0.,  0., -2.],
       [ 0.,  0., -2.,  0.]])

In [8]:
xA = (np.array(S)).dot(np.array(W2))
tA = np.sign(xA)
comparison = tA == S

xA = (np.array(S2)).dot(np.array(W2))
tA = np.sign(xA)
comparison2 = tA == S2
comparison.all() and comparison2.all()

True

# part3

In [22]:
# S= [1,1,1,-1]
S3 = [-1,-1,-1,1]    
W3 = np.outer(S3,S3)  + np.outer(S,S) - 2*np.identity(4) #+ np.outer(S2,S2)

In [23]:
W3

array([[ 0.,  2.,  2., -2.],
       [ 2.,  0.,  2., -2.],
       [ 2.,  2.,  0., -2.],
       [-2., -2., -2.,  0.]])

In [24]:
xA = (np.array(S)).dot(np.array(W3))
tA = np.sign(xA)
comparison = tA == S
xA = (np.array(S3)).dot(np.array(W3))
tA = np.sign(xA)
comparison3 = tA == S3
(comparison.all() and comparison3.all())

True

# part4

In [12]:
S4 = [-1,-1,1,-1]
W4 = np.outer(S,S) + np.outer(S2,S2) + np.outer(S4,S4) - 3*np.identity(4)

In [13]:
W4

array([[ 0.,  3., -1.,  1.],
       [ 3.,  0., -1.,  1.],
       [-1., -1.,  0., -3.],
       [ 1.,  1., -3.,  0.]])

In [14]:
xA = (np.array(S)).dot(np.array(W4))
tA = np.sign(xA)
comparison = tA == S
xA = (np.array(S2)).dot(np.array(W4))
tA = np.sign(xA)
comparison2 = tA == S2
xA = (np.array(S4)).dot(np.array(W4))
tA = np.sign(xA)
comparison4 = tA == S4
comparison.all() and comparison2.all() and comparison4.all()

True

In [15]:
S5 = [-1,-1,-1,1]
W5 = np.outer(S,S) + np.outer(S2,S2) + np.outer(S4,S4) + np.outer(S5,S5) - 4*np.identity(4)

In [16]:
xA = (np.array(S)).dot(np.array(W5))
tA = np.sign(xA)
comparison = tA == S
xA = (np.array(S2)).dot(np.array(W5))
tA = np.sign(xA)
comparison2 = tA == S2
xA = (np.array(S4)).dot(np.array(W5))
tA = np.sign(xA)
comparison4 = tA == S4
xA = (np.array(S5)).dot(np.array(W5))
tA = np.sign(xA)
comparison5 = tA == S5

comparison.all() and comparison2.all() and comparison4.all() and comparison5.all()

True

In [17]:
S6 = [1,-1,-1,-1]
W6 = np.outer(S,S) + np.outer(S2,S2) + np.outer(S4,S4) + np.outer(S5,S5) + np.outer(S6,S6) - 5*np.identity(4)

In [18]:
xA = (np.array(S)).dot(np.array(W6))
tA = np.sign(xA)
comparison = tA == S
xA = (np.array(S2)).dot(np.array(W6))
tA = np.sign(xA)
comparison2 = tA == S2
xA = (np.array(S4)).dot(np.array(W6))
tA = np.sign(xA)
comparison4 = tA == S4
xA = (np.array(S5)).dot(np.array(W6))
tA = np.sign(xA)
comparison5 = tA == S5
xA = (np.array(S6)).dot(np.array(W6))
tA = np.sign(xA)
comparison6 = tA == S6

comparison.all() and comparison2.all() and comparison4.all() and comparison5.all() and comparison6.all()

False

# part5

In [28]:
S7 = [1,1,1,-1]
S8 = [1,1,-1,1]
S9 = [1,-1,1,1]
W7 = np.outer(S7,S7) + np.outer(S8,S8) + np.outer(S9,S9)  - 3*np.identity(4)
xA = (np.array(S7)).dot(np.array(W7))
tA = np.sign(xA)
comparison7 = tA == S7
xA = (np.array(S8)).dot(np.array(W7))
tA = np.sign(xA)
comparison8 = tA == S8
xA = (np.array(S9)).dot(np.array(W7))
tA = np.sign(xA)
comparison9 = tA == S9
comparison7.all() and comparison8.all() and comparison9.all()

True